require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
pod 'Braspag3Ds', :git => 'https://github.com/DeveloperCielo/3ds-ios.git', :tag => '1.0.11'


target 'authentication3DS' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'authentication3DSTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'authentication3DS-tvOS' do
  # Pods for authentication3DS-tvOS

  target 'authentication3DS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
